# serverless.yml

service: shield-delivery

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  versionFunctions: false

functions:
  get-badge:
    handler: index.handler
    events:
      - http:
          path: get-badge
          method: get
          cors: true
      - http:
          path: get-badge-table
          method: get
          cors: true
    memorySize: 256 # optional, in MB, default is 1024
    timeout: 5 # optional, in seconds, default is 6
    reservedConcurrency: 10
    description: A serverless function that serves individual badges for use in GitHub repos.
    tags:
      project: devpost-badge-gen

package:
  include:
    - assets/**

plugins:
  - serverless-offline
  - serverless-domain-manager

custom:
  customDomain:
    domainName: badges.devpost-shields.com
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true